### ISSUE TITLE
implement category page header on mobile

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#112]
@rcar1115 this has come up as important as the boys are showing Rdio tomorrow. Can you refine this mobile view.
- hide the category description
- scale the logo down by 50%

**Comment by raulfelix** [comment]
The only way I can scale it down to 50% is if you standardise the size you are uploading otherwise Ill have to write a whole bunch of JS to measure the original and scale it based on screen width.

Can we standardise or is it too random a set of logo's that will get uploaded? @jonnybrian 

e.g. the red bull logo is 240 x 40 so I if I know this I can make the container 240px and set width 50% of that. With the Rdio one on the yardy because the width is 129px it scales up and looks blurry when set to 50%.

**Comment by raulfelix** [comment]
This also goes for "adding the category logo to homepage carousel" #86

**Comment by jonnybrian** [comment]
Yeah its tricky with transparent pngs huh... Do both dimensions have to match or can we just say standardise the width and scale down proportionally @rcar1115 ?

**Comment by raulfelix** [comment]
The width is enough but you still cant vary the height too much of it will look off. @jonnybrian

**Comment by jonnybrian** [comment]
ok so to recap, new logo size for desktop category header is 180 x 90 @rcar1115

**Comment by raulfelix** [comment]
I have applied the dimensions to the logo @jonnybrian
