### ISSUE TITLE
Page assembly/grid

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#17]
The overall page layout needs to be defined in order to proceed populating with modules. 
Grid layout will be used in line with the design.

The following needs to be determined prior to proceeding with this task @jonnybrian
- Maximum layout width
- Gutter size
- Gutter behaviour i.e. fixed or fluid?
- Gutter changes across breakpoints

**Comment by jonnybrian** [comment]
Yo blud,
My plan is to stick with the exact properties of the CBA responsive grid, also utilising the same breakpoints we developed back in the glory days, I haven't gained any new insights on preferential values and properties since we worked on that grid. 

@rcar1115 do you need me to go though those values again or do you have them to hand?

**Comment by raulfelix** [comment]
Sweet! @jonnybrian I still have it all at hand so we are a go for grid. Thanks
