### ISSUE TITLE
image width and quality within article body

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#62]
Image width should be set to 10 columns of the grid, where as the text is set to 8.

Also when the images upload to the library they seem to compress heavily again, can you remove that altogether please so the image quality remains at what the user uploads it at...

Respect.

**Comment by jonnybrian** [comment]
@rcar1115 I have since noticed the image width is correct for the news article: http://www.theyardy.info/news/music/the-singing-sensation-is-back-down-under/

is it something I've done wrong when uploading images to the article body for the featured posts?

**Comment by raulfelix** [comment]
> images upload to the library they seem to compress heavily

ok so the compression is Wordpress being kind to you and creating different size images. When you insert the image into a post you need to specify which dimensions to use and whether to wrap the image in a link etc. The options are full size, medium, thumbnail and so on. 

> Image width should be set to 10 columns of the grid, where as the text is set to 8.

The editor is a bitch sometimes. It automatically wraps img tags in p tags because an img is not by default a block level element. Not sure at this point if that can be fixed. The way to solve it at the moment is to edit in "text" mode and wrap any img tag in a div element. 
This needs to be done because there are now structural rows in the editor so I have to add padding to content to indent it more than images... we can discuss

**Comment by raulfelix** [comment]
OK added a piece of code to strip the p tags but you will need to set the image to link to "none" when uploading an image to a post.
