### ISSUE TITLE
hosting and ftp details

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#67]

**Comment by jonnybrian** [comment]
@rcar1115 from their current hosting account where do you access all the cPanel stuff to create subdomains etc?

**Comment by raulfelix** [comment]
This hosting company does not provide your standard cpanel. Its a bit more hardcore.

Most stuff will be done through ftp/shell. For the subdomain I can add that for you through editing the .htaccess file associated with the server. You let me know what you want and ill get in there. 

ps. I removed the login info above just because this is a public account... Its in our emails now.

**Comment by jonnybrian** [comment]
https://github.com/lifewithoutandy/warhol/issues/80 @rcar1115 now covers this off for now

**Comment by raulfelix** [comment]
Just a note on the hosting which you asked me about last time. They have a private server which is good and most likely necessary for a high traffic site. What I think is sending the cost so high though is that the company specialise in ExpressionEngine hosting which is a non open source cms and so they can charge more.

They may be able to get a private server with all the benefits for less as you found @jonnybrian
